# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Library CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the GitHub repo on the machine
    - uses: actions/checkout@v4
    - name: Install Node.js 18.x on the machine
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install program dependencies
      run: npm install
    - name: Install Playwright Tests
      run: npm install -D @playwright/test
    - name: Install Playwright 
      run: npx playwright install
    - name: Start the Server
      run: npm run server
    - name: Start the Application
      run: npm run start
    - name: Run the Tests
      run: npm run test
